version: 2.1

jobs: 
  build:
    docker:
    - image: circleci/openjdk:11-jdk-browsers

    steps: 
    - checkout
    - run: 
        ./gradlew build 
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;

    - store_test_results:
        path: ~/junit
      
    - store_artifacts:
        path: ~/junit

    - store_artifacts:
        path: simulator-core/libs/simulator-core.jar

  sonar-static-analysis:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    
    steps:
    - checkout
    - run:
        name: sonarqube static analysis
        command: ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$CIRCLE_BRANCH

  publish-to-jcenter:
    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:
    - checkout
    - run:
        name: publish artifact
        command: ./gradlew bintrayUpload

workflows:
  default:
    jobs:
    - build
    - sonar-static-analysis
    - publish-to-jcenter-approval:
        requires:
          - build
          - sonar-static-analysis
        type: approval
    - publish-to-jcenter:
        requires:
            - publish-to-jcenter-approval
